/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ShopRingsRouteImport } from './routes/shop.rings'
import { Route as ShopOpenableKadaRouteImport } from './routes/shop.openable-kada'
import { Route as ShopNecklacesRouteImport } from './routes/shop.necklaces'
import { Route as ShopMangalsutraRouteImport } from './routes/shop.mangalsutra'
import { Route as ShopEarringsRouteImport } from './routes/shop.earrings'
import { Route as ShopChainPendantsRouteImport } from './routes/shop.chain-pendants'
import { Route as ShopChainBraceletsRouteImport } from './routes/shop.chain-bracelets'
import { Route as ShopBraceletsRouteImport } from './routes/shop.bracelets'
import { Route as ShopBanglesRouteImport } from './routes/shop.bangles'
import { Route as ShopAnkletsRouteImport } from './routes/shop.anklets'
import { Route as AdminPromotionsRouteImport } from './routes/admin.promotions'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminContentRouteImport } from './routes/admin.content'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ShopRingsRoute = ShopRingsRouteImport.update({
  id: '/shop/rings',
  path: '/shop/rings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopOpenableKadaRoute = ShopOpenableKadaRouteImport.update({
  id: '/shop/openable-kada',
  path: '/shop/openable-kada',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopNecklacesRoute = ShopNecklacesRouteImport.update({
  id: '/shop/necklaces',
  path: '/shop/necklaces',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopMangalsutraRoute = ShopMangalsutraRouteImport.update({
  id: '/shop/mangalsutra',
  path: '/shop/mangalsutra',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopEarringsRoute = ShopEarringsRouteImport.update({
  id: '/shop/earrings',
  path: '/shop/earrings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopChainPendantsRoute = ShopChainPendantsRouteImport.update({
  id: '/shop/chain-pendants',
  path: '/shop/chain-pendants',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopChainBraceletsRoute = ShopChainBraceletsRouteImport.update({
  id: '/shop/chain-bracelets',
  path: '/shop/chain-bracelets',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopBraceletsRoute = ShopBraceletsRouteImport.update({
  id: '/shop/bracelets',
  path: '/shop/bracelets',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopBanglesRoute = ShopBanglesRouteImport.update({
  id: '/shop/bangles',
  path: '/shop/bangles',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopAnkletsRoute = ShopAnkletsRouteImport.update({
  id: '/shop/anklets',
  path: '/shop/anklets',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPromotionsRoute = AdminPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/shop/anklets': typeof ShopAnkletsRoute
  '/shop/bangles': typeof ShopBanglesRoute
  '/shop/bracelets': typeof ShopBraceletsRoute
  '/shop/chain-bracelets': typeof ShopChainBraceletsRoute
  '/shop/chain-pendants': typeof ShopChainPendantsRoute
  '/shop/earrings': typeof ShopEarringsRoute
  '/shop/mangalsutra': typeof ShopMangalsutraRoute
  '/shop/necklaces': typeof ShopNecklacesRoute
  '/shop/openable-kada': typeof ShopOpenableKadaRoute
  '/shop/rings': typeof ShopRingsRoute
  '/admin/': typeof AdminIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/shop/anklets': typeof ShopAnkletsRoute
  '/shop/bangles': typeof ShopBanglesRoute
  '/shop/bracelets': typeof ShopBraceletsRoute
  '/shop/chain-bracelets': typeof ShopChainBraceletsRoute
  '/shop/chain-pendants': typeof ShopChainPendantsRoute
  '/shop/earrings': typeof ShopEarringsRoute
  '/shop/mangalsutra': typeof ShopMangalsutraRoute
  '/shop/necklaces': typeof ShopNecklacesRoute
  '/shop/openable-kada': typeof ShopOpenableKadaRoute
  '/shop/rings': typeof ShopRingsRoute
  '/admin': typeof AdminIndexRoute
  '/shop': typeof ShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/shop/anklets': typeof ShopAnkletsRoute
  '/shop/bangles': typeof ShopBanglesRoute
  '/shop/bracelets': typeof ShopBraceletsRoute
  '/shop/chain-bracelets': typeof ShopChainBraceletsRoute
  '/shop/chain-pendants': typeof ShopChainPendantsRoute
  '/shop/earrings': typeof ShopEarringsRoute
  '/shop/mangalsutra': typeof ShopMangalsutraRoute
  '/shop/necklaces': typeof ShopNecklacesRoute
  '/shop/openable-kada': typeof ShopOpenableKadaRoute
  '/shop/rings': typeof ShopRingsRoute
  '/admin/': typeof AdminIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/admin'
    | '/contact'
    | '/admin/content'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/promotions'
    | '/shop/anklets'
    | '/shop/bangles'
    | '/shop/bracelets'
    | '/shop/chain-bracelets'
    | '/shop/chain-pendants'
    | '/shop/earrings'
    | '/shop/mangalsutra'
    | '/shop/necklaces'
    | '/shop/openable-kada'
    | '/shop/rings'
    | '/admin/'
    | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/contact'
    | '/admin/content'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/promotions'
    | '/shop/anklets'
    | '/shop/bangles'
    | '/shop/bracelets'
    | '/shop/chain-bracelets'
    | '/shop/chain-pendants'
    | '/shop/earrings'
    | '/shop/mangalsutra'
    | '/shop/necklaces'
    | '/shop/openable-kada'
    | '/shop/rings'
    | '/admin'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/admin'
    | '/contact'
    | '/admin/content'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/promotions'
    | '/shop/anklets'
    | '/shop/bangles'
    | '/shop/bracelets'
    | '/shop/chain-bracelets'
    | '/shop/chain-pendants'
    | '/shop/earrings'
    | '/shop/mangalsutra'
    | '/shop/necklaces'
    | '/shop/openable-kada'
    | '/shop/rings'
    | '/admin/'
    | '/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  ShopAnkletsRoute: typeof ShopAnkletsRoute
  ShopBanglesRoute: typeof ShopBanglesRoute
  ShopBraceletsRoute: typeof ShopBraceletsRoute
  ShopChainBraceletsRoute: typeof ShopChainBraceletsRoute
  ShopChainPendantsRoute: typeof ShopChainPendantsRoute
  ShopEarringsRoute: typeof ShopEarringsRoute
  ShopMangalsutraRoute: typeof ShopMangalsutraRoute
  ShopNecklacesRoute: typeof ShopNecklacesRoute
  ShopOpenableKadaRoute: typeof ShopOpenableKadaRoute
  ShopRingsRoute: typeof ShopRingsRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/shop/rings': {
      id: '/shop/rings'
      path: '/shop/rings'
      fullPath: '/shop/rings'
      preLoaderRoute: typeof ShopRingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/openable-kada': {
      id: '/shop/openable-kada'
      path: '/shop/openable-kada'
      fullPath: '/shop/openable-kada'
      preLoaderRoute: typeof ShopOpenableKadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/necklaces': {
      id: '/shop/necklaces'
      path: '/shop/necklaces'
      fullPath: '/shop/necklaces'
      preLoaderRoute: typeof ShopNecklacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/mangalsutra': {
      id: '/shop/mangalsutra'
      path: '/shop/mangalsutra'
      fullPath: '/shop/mangalsutra'
      preLoaderRoute: typeof ShopMangalsutraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/earrings': {
      id: '/shop/earrings'
      path: '/shop/earrings'
      fullPath: '/shop/earrings'
      preLoaderRoute: typeof ShopEarringsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/chain-pendants': {
      id: '/shop/chain-pendants'
      path: '/shop/chain-pendants'
      fullPath: '/shop/chain-pendants'
      preLoaderRoute: typeof ShopChainPendantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/chain-bracelets': {
      id: '/shop/chain-bracelets'
      path: '/shop/chain-bracelets'
      fullPath: '/shop/chain-bracelets'
      preLoaderRoute: typeof ShopChainBraceletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/bracelets': {
      id: '/shop/bracelets'
      path: '/shop/bracelets'
      fullPath: '/shop/bracelets'
      preLoaderRoute: typeof ShopBraceletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/bangles': {
      id: '/shop/bangles'
      path: '/shop/bangles'
      fullPath: '/shop/bangles'
      preLoaderRoute: typeof ShopBanglesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/anklets': {
      id: '/shop/anklets'
      path: '/shop/anklets'
      fullPath: '/shop/anklets'
      preLoaderRoute: typeof ShopAnkletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/promotions': {
      id: '/admin/promotions'
      path: '/promotions'
      fullPath: '/admin/promotions'
      preLoaderRoute: typeof AdminPromotionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminContentRoute: typeof AdminContentRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminPromotionsRoute: typeof AdminPromotionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminContentRoute: AdminContentRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminPromotionsRoute: AdminPromotionsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  ShopAnkletsRoute: ShopAnkletsRoute,
  ShopBanglesRoute: ShopBanglesRoute,
  ShopBraceletsRoute: ShopBraceletsRoute,
  ShopChainBraceletsRoute: ShopChainBraceletsRoute,
  ShopChainPendantsRoute: ShopChainPendantsRoute,
  ShopEarringsRoute: ShopEarringsRoute,
  ShopMangalsutraRoute: ShopMangalsutraRoute,
  ShopNecklacesRoute: ShopNecklacesRoute,
  ShopOpenableKadaRoute: ShopOpenableKadaRoute,
  ShopRingsRoute: ShopRingsRoute,
  ShopIndexRoute: ShopIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
